### ISSUE TITLE
poluting sys.path

### ISSUE THREAD

**Issue by eightnoteight** [llazzaro/packyou#3]
Hi,

packyou is an awesome library. for sharing examples, snippets etc,.. 

but the `update_sys_path` method's `os.walk`  is seriously poluting the sys.path, at some point it becomes unusable as it includes every possible directory of a python project into sys.path i.e when some project has multiple `util.py` files then packyou just doesn't work. or if we use different projects having `util.py` files then again we can't use packyou

![screenshot from 2016-09-22 21-37-30](https://cloud.githubusercontent.com/assets/6435796/18756717/91b05460-810e-11e6-927e-a2f29542cedb.png)

So to be more deterministic about the purpose of packyou it is better to drop support for implicit relative import statements. Just support explicit relative imports and full package name imports.

If we drop it then we don't need to pollute sys.path at all. safe & secure

PS: this way we can even say that we support packages if they use explicit import statements. #1

**Comment by llazzaro** [comment]
Totally agree on this. 
One point, we need to support relative imports since the project it self could use relative imports inside.
However it is only required to add the root path to the sys.path not all the paths.

**Comment by eightnoteight** [comment]
Ok I got a little bit confused on explicit relative imports, ranted about dropping support, although it's not needed.

So yeah, we should just add root path of the git repo to the sys.path

**Comment by llazzaro** [comment]
This issue is fixed not. I removed the hack that was using the sys.path.
